# -*- coding: utf-8 -*-
"""TRAINING_MODULE

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zGvPZxbGBvuY-bGfLfqHHTOaHydm-toR
"""

import os

ravdess_path = r"dataset/Audio_Speech_Actors_01-24"
ravdess_list_folder = os.listdir(ravdess_path)

ravdess_list_folder

ravdess_list = []

for sub_folder in ravdess_list_folder:
    sub_folder_list = os.listdir(ravdess_path+"/"+sub_folder)
    for path in sub_folder_list:
        ravdess_list.append(ravdess_path+"/"+sub_folder+"/"+path)

ravdess_list[:20]

ravdess_list[6].split('/')[-1]
savee_path = r"dataset\AudioData"
savee_list_folder = os.listdir(savee_path)
savee_list_folder
savee_list = []

for sub_folder in savee_list_folder:
    sub_folder_list = os.listdir(savee_path+"/"+sub_folder)
    for path in sub_folder_list:
        savee_list.append(savee_path+"/"+sub_folder+"/"+path)
        savee_list[:20]
