# -*- coding: utf-8 -*-
"""TRAINING_MODULE

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zGvPZxbGBvuY-bGfLfqHHTOaHydm-toR
"""

import os

ravdess_path = r"dataset/Audio_Speech_Actors_01-24"
ravdess_list_folder = os.listdir(ravdess_path)

ravdess_list_folder

ravdess_list = []

for sub_folder in ravdess_list_folder:
    sub_folder_list = os.listdir(ravdess_path+"/"+sub_folder)
    for path in sub_folder_list:
        ravdess_list.append(ravdess_path+"/"+sub_folder+"/"+path)

ravdess_list[:20]